version: '3.7'
services:
  api:
    image: 'eyadroshnikov/atari-breakout-backend'
    environment:
      POSTGRES_HOST: 'atari_breakout_postgres_db'
      POSTGRES_PORT: '5432'
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '3000:3000'
    restart: on-failure
  postgres:
    image: postgres:16
    container_name: atari_breakout_postgres_db
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: